### ISSUE TITLE
Search page is not working

### ISSUE THREAD

**Issue by illumination-k** [illumination-k/blog#5]
considering amp-lightbox + amp-form + amp-list

**Comment by illumination-k** [comment]
AMP optimizer problem?

```
[GET] /search
21:13:24:69
2022-04-10T12:13:34.737Z	caf613ef-0f5e-453c-9a7b-91ef0b8d91a8	ERROR	AMP Optimizer ERROR Could not write cache file Error: EROFS: read-only file system, mkdir '/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/.cache'
    at mkdirSync (fs.js:1013:3)
    at FileSystemCache.set (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:783)
    at fetchLatestRuntimeData_ (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:17068)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async fetchAmpRuntimeVersion_ (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:16502)
    at async initRuntimeVersion (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:16188)
    at async fetchRuntimeParameters (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:15017)
    at async DomTransformer.transformTree (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:7151)
    at async DomTransformer.transformHtml (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:7035)
    at async process.browser.process.env.__NEXT_OPTIMIZE_FONTS.postProcess.getFontDefinition.getFontDefinition (/var/task/node_modules/next/dist/server/render.js:1078:20) {
  errno: -30,
  syscall: 'mkdir',
  code: 'EROFS',
  path: '/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/.cache'
}
2022-04-10T12:13:34.759Z	caf613ef-0f5e-453c-9a7b-91ef0b8d91a8	ERROR	AMP Optimizer ERROR Could not write cache file Error: EROFS: read-only file system, mkdir '/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/.cache'
    at mkdirSync (fs.js:1013:3)
    at FileSystemCache.set (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:783)
    at downloadAmpRuntimeStyles_ (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:18021)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async fetchAmpRuntimeStyles_ (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:17433)
    at async initRuntimeStyles (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:15781)
    at async fetchRuntimeParameters (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:15049)
    at async DomTransformer.transformTree (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:7151)
    at async DomTransformer.transformHtml (/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/index.js:1:7035)
    at async process.browser.process.env.__NEXT_OPTIMIZE_FONTS.postProcess.getFontDefinition.getFontDefinition (/var/task/node_modules/next/dist/server/render.js:1078:20) {
  errno: -30,
  syscall: 'mkdir',
  code: 'EROFS',
  path: '/var/task/node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/.cache'
}
2022-04-10T12:13:34.775Z caf613ef-0f5e-453c-9a7b-91ef0b8d91a8 Task timed out after 10.02 seconds
```

**Comment by illumination-k** [comment]
Custom amp optimizer

https://github.com/vercel/next.js/blob/4a7ab34baf932c102fbf281660f09f7eb98c4b74/test/integration/amphtml-custom-optimizer/next.config.js
